import type { SkillTrackRecommendation } from "@/lib/skills/types"

const link = (title: string, url: string, provider: string) => ({ title, url, provider })

export const skillRecommendationsCatalog: SkillTrackRecommendation[] = [
  {
    id: "ai-engineering-fundamentals",
    title: "AI Engineering Fundamentals",
    domain: "AI",
    demandScore: 95,
    trendLabel: "High Growth",
    difficulty: "Beginner",
    estimatedMonths: 4,
    summary: "Build practical AI app foundations using Python, ML basics, and modern LLM tooling.",
    whyNow: "Most software teams now expect engineers to ship AI-assisted workflows.",
    tags: ["ai", "python", "llm", "fundamentals", "ml"],
    roadmapMilestones: [
      "Learn Python fundamentals for data and automation",
      "Review statistics basics: probability, distributions, hypothesis testing",
      "Practice numpy and pandas data manipulation",
      "Train baseline ML models with scikit-learn",
      "Understand neural network fundamentals",
      "Use embeddings and vector search concepts",
      "Build first LLM app with retrieval augmented generation",
      "Evaluate model outputs with simple quality metrics",
      "Deploy AI API endpoints with logging",
      "Ship one portfolio AI assistant project",
    ],
    resources: {
      officialDocs: [
        link("Python Docs", "https://docs.python.org/3/", "Python"),
        link("Scikit-learn User Guide", "https://scikit-learn.org/stable/user_guide.html", "Scikit-learn"),
      ],
      youtubeChannels: [
        link("freeCodeCamp AI Courses", "https://www.youtube.com/@freecodecamp", "freeCodeCamp"),
        link("DeepLearningAI", "https://www.youtube.com/@Deeplearningai", "DeepLearningAI"),
      ],
      labsHandsOn: [
        link("Kaggle Learn", "https://www.kaggle.com/learn", "Kaggle"),
      ],
      roadmaps: [
        link("AI and Data Scientist Roadmap", "https://roadmap.sh/ai-data-scientist", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("Made With ML", "https://madewithml.com/", "Made With ML"),
        link("Google ML Crash Course", "https://developers.google.com/machine-learning/crash-course", "Google"),
      ],
      projectIdeas: [
        "Build a resume analyzer with skill-gap suggestions",
        "Create a support-ticket classifier with explanation output",
      ],
    },
  },
  {
    id: "llm-application-development",
    title: "LLM Application Development",
    domain: "AI",
    demandScore: 97,
    trendLabel: "Surging",
    difficulty: "Intermediate",
    estimatedMonths: 5,
    summary: "Design robust chat, retrieval, and agentic applications around foundation models.",
    whyNow: "LLM-powered features are becoming baseline expectations in SaaS products.",
    tags: ["llm", "rag", "agents", "ai", "product"],
    roadmapMilestones: [
      "Learn transformer and tokenization fundamentals",
      "Implement prompt templates and output schemas",
      "Add retrieval with embeddings and vector databases",
      "Design robust context-window strategies",
      "Integrate tool calling and function execution",
      "Add guardrails and content safety checks",
      "Instrument latency, cost, and quality telemetry",
      "Implement fallback and retry strategies",
      "Run offline evals and prompt regression tests",
      "Launch a production LLM feature with monitoring",
    ],
    resources: {
      officialDocs: [
        link("OpenAI Platform Docs", "https://platform.openai.com/docs", "OpenAI"),
        link("LangChain Docs", "https://docs.langchain.com/", "LangChain"),
      ],
      youtubeChannels: [
        link("LangChain", "https://www.youtube.com/@LangChain", "LangChain"),
        link("OpenAI", "https://www.youtube.com/@OpenAI", "OpenAI"),
      ],
      labsHandsOn: [
        link("LangChain Tutorials", "https://python.langchain.com/docs/tutorials/", "LangChain"),
      ],
      roadmaps: [
        link("AI Engineer Roadmap", "https://roadmap.sh/ai-engineer", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("LlamaIndex Learn", "https://www.llamaindex.ai/learn", "LlamaIndex"),
        link("Anthropic Prompt Engineering", "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview", "Anthropic"),
      ],
      projectIdeas: [
        "Build a RAG-based internal policy assistant",
        "Create a meeting summarizer with action item extraction",
      ],
    },
  },
  {
    id: "mlops-model-serving",
    title: "MLOps and Model Serving",
    domain: "AI",
    demandScore: 90,
    trendLabel: "High Growth",
    difficulty: "Advanced",
    estimatedMonths: 6,
    summary: "Operationalize training, deployment, monitoring, and lifecycle governance for ML systems.",
    whyNow: "Teams need reliable model operations, not only prototypes.",
    tags: ["mlops", "ml", "deployment", "monitoring", "pipelines"],
    roadmapMilestones: [
      "Version datasets and model artifacts",
      "Design reproducible training pipelines",
      "Automate experiments and metadata tracking",
      "Build CI/CD for model validation and release",
      "Serve models with low-latency APIs",
      "Implement drift and performance monitoring",
      "Set up feature stores and data contracts",
      "Add rollback and shadow deployment workflows",
      "Handle governance and audit requirements",
      "Run post-deployment model health reviews",
    ],
    resources: {
      officialDocs: [
        link("MLflow Docs", "https://mlflow.org/docs/latest/index.html", "MLflow"),
        link("Kubeflow Docs", "https://www.kubeflow.org/docs/", "Kubeflow"),
      ],
      youtubeChannels: [
        link("MLOps Community", "https://www.youtube.com/@MLOpsCommunity", "MLOps Community"),
        link("Databricks", "https://www.youtube.com/@Databricks", "Databricks"),
      ],
      labsHandsOn: [
        link("Google Cloud MLOps Labs", "https://www.cloudskillsboost.google/paths/17", "Google Cloud Skills Boost"),
      ],
      roadmaps: [
        link("MLOps Roadmap", "https://roadmap.sh/mlops", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("Made With ML MLOps", "https://madewithml.com/courses/mlops/", "Made With ML"),
        link("AWS MLOps Whitepaper", "https://docs.aws.amazon.com/whitepapers/latest/mlops-lens/mlops-lens.html", "AWS"),
      ],
      projectIdeas: [
        "Deploy a churn model with drift alerts",
        "Build a retraining pipeline with approval gates",
      ],
    },
  },
  {
    id: "data-engineering-python",
    title: "Data Engineering with Python",
    domain: "Data",
    demandScore: 92,
    trendLabel: "High Demand",
    difficulty: "Intermediate",
    estimatedMonths: 6,
    summary: "Create reliable data ingestion, transformation, warehousing, and analytics pipelines.",
    whyNow: "AI and analytics initiatives depend on strong data infrastructure.",
    tags: ["data", "etl", "python", "warehouse", "spark"],
    roadmapMilestones: [
      "Master SQL for analytics and transformations",
      "Build Python ETL pipelines",
      "Design batch ingestion jobs",
      "Add streaming ingestion basics",
      "Model data for warehouse analytics",
      "Implement orchestration with schedulers",
      "Optimize data quality checks",
      "Apply partitioning and performance tuning",
      "Set up lineage and observability",
      "Ship an end-to-end analytics pipeline",
    ],
    resources: {
      officialDocs: [
        link("Apache Airflow Docs", "https://airflow.apache.org/docs/", "Apache"),
        link("dbt Docs", "https://docs.getdbt.com/", "dbt Labs"),
      ],
      youtubeChannels: [
        link("DataTalksClub", "https://www.youtube.com/@DataTalksClub", "DataTalksClub"),
        link("Seattle Data Guy", "https://www.youtube.com/@SeattleDataGuy", "Seattle Data Guy"),
      ],
      labsHandsOn: [
        link("Data Engineering Zoomcamp", "https://github.com/DataTalksClub/data-engineering-zoomcamp", "DataTalksClub"),
      ],
      roadmaps: [
        link("Data Engineer Roadmap", "https://roadmap.sh/data-analyst", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("Fundamentals of Data Engineering Notes", "https://www.startdataengineering.com/", "Start Data Engineering"),
        link("Google Cloud Data Engineering Learning", "https://cloud.google.com/learn/data-engineering", "Google Cloud"),
      ],
      projectIdeas: [
        "Build a pipeline from public API to analytics dashboard",
        "Create a streaming event aggregation service",
      ],
    },
  },
  {
    id: "backend-api-engineering",
    title: "Backend API Engineering",
    domain: "Backend",
    demandScore: 93,
    trendLabel: "Always Needed",
    difficulty: "Beginner",
    estimatedMonths: 5,
    summary: "Develop scalable backend services, APIs, and data access layers.",
    whyNow: "Every product stack still depends on reliable backend services.",
    tags: ["backend", "api", "node", "services", "fundamentals"],
    roadmapMilestones: [
      "Learn HTTP, REST, and status code semantics",
      "Build CRUD APIs with validation",
      "Design authentication and authorization",
      "Add structured logging and metrics",
      "Implement caching and pagination",
      "Model relational and NoSQL persistence",
      "Handle queues and async workflows",
      "Improve reliability with retries and idempotency",
      "Write integration and contract tests",
      "Deploy API with observability and scaling",
    ],
    resources: {
      officialDocs: [
        link("Node.js Docs", "https://nodejs.org/docs/latest/api/", "Node.js"),
        link("Express Docs", "https://expressjs.com/", "Express"),
      ],
      youtubeChannels: [
        link("Traversy Media", "https://www.youtube.com/@TraversyMedia", "Traversy Media"),
        link("Fireship", "https://www.youtube.com/@Fireship", "Fireship"),
      ],
      labsHandsOn: [
        link("NodeSchool", "https://nodeschool.io/", "NodeSchool"),
      ],
      roadmaps: [
        link("Backend Roadmap", "https://roadmap.sh/backend", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("Microsoft REST API Guidelines", "https://github.com/microsoft/api-guidelines", "Microsoft"),
        link("Stripe API Design Principles", "https://stripe.com/blog/api-versioning", "Stripe"),
      ],
      projectIdeas: [
        "Create a multi-tenant task API with JWT auth",
        "Build a rate-limited payments mock service",
      ],
    },
  },
  {
    id: "system-design-distributed",
    title: "System Design and Distributed Systems",
    domain: "Architecture",
    demandScore: 88,
    trendLabel: "Critical Skill",
    difficulty: "Advanced",
    estimatedMonths: 6,
    summary: "Architect resilient, scalable systems with clear tradeoffs and reliability goals.",
    whyNow: "As products scale, design decisions become key bottlenecks.",
    tags: ["system design", "distributed", "architecture", "scalability"],
    roadmapMilestones: [
      "Understand availability, consistency, and latency tradeoffs",
      "Design data partitioning and replication",
      "Use caching at multiple layers",
      "Work with queues and event-driven patterns",
      "Implement idempotent and fault-tolerant flows",
      "Design multi-region read/write patterns",
      "Choose storage engines by workload",
      "Model SLOs and capacity planning",
      "Run architecture reviews and threat modeling",
      "Document architecture decisions with tradeoffs",
    ],
    resources: {
      officialDocs: [
        link("Google SRE Book", "https://sre.google/sre-book/table-of-contents/", "Google"),
        link("AWS Well-Architected", "https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html", "AWS"),
      ],
      youtubeChannels: [
        link("Gaurav Sen", "https://www.youtube.com/@gkcs", "Gaurav Sen"),
        link("ByteByteGo", "https://www.youtube.com/@ByteByteGo", "ByteByteGo"),
      ],
      labsHandsOn: [
        link("System Design Primer", "https://github.com/donnemartin/system-design-primer", "GitHub"),
      ],
      roadmaps: [
        link("Software Architect Roadmap", "https://roadmap.sh/software-architect", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("Martin Kleppmann Notes", "https://dataintensive.net/", "Data Intensive"),
        link("High Scalability", "http://highscalability.com/", "High Scalability"),
      ],
      projectIdeas: [
        "Design a URL shortener with analytics at scale",
        "Design a chat backend with ordering and offline delivery",
      ],
    },
  },
  {
    id: "aws-cloud-engineering",
    title: "AWS Cloud Engineering",
    domain: "Cloud",
    demandScore: 91,
    trendLabel: "High Demand",
    difficulty: "Intermediate",
    estimatedMonths: 5,
    summary: "Build, secure, and operate cloud-native workloads on AWS.",
    whyNow: "Cloud platform skills remain core requirements in most engineering teams.",
    tags: ["aws", "cloud", "infra", "networking", "iam"],
    roadmapMilestones: [
      "Understand AWS global infrastructure and pricing basics",
      "Master IAM, policies, and least privilege access",
      "Deploy compute with EC2, Lambda, and ECS",
      "Work with S3, EBS, and data lifecycle management",
      "Design VPC, subnets, and network security controls",
      "Implement IaC with CloudFormation or Terraform",
      "Configure observability with CloudWatch",
      "Set up CI/CD to AWS environments",
      "Optimize cost and performance with tagging",
      "Ship a production-ready AWS reference architecture",
    ],
    resources: {
      officialDocs: [
        link("AWS Documentation", "https://docs.aws.amazon.com/", "AWS"),
        link("AWS Skill Builder", "https://explore.skillbuilder.aws/learn", "AWS"),
      ],
      youtubeChannels: [
        link("AWS Events", "https://www.youtube.com/@AWSEventsChannel", "AWS"),
        link("freeCodeCamp Cloud", "https://www.youtube.com/@freecodecamp", "freeCodeCamp"),
      ],
      labsHandsOn: [
        link("AWS Workshops", "https://workshops.aws/", "AWS"),
      ],
      roadmaps: [
        link("AWS Roadmap", "https://roadmap.sh/aws", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("AWS Architecture Center", "https://aws.amazon.com/architecture/", "AWS"),
        link("AWS Prescriptive Guidance", "https://docs.aws.amazon.com/prescriptive-guidance/latest/guidance.html", "AWS"),
      ],
      projectIdeas: [
        "Deploy a serverless image-processing pipeline",
        "Build a secure multi-environment web app platform",
      ],
    },
  },
  {
    id: "kubernetes-platform-operations",
    title: "Kubernetes Platform Operations",
    domain: "Containers",
    demandScore: 89,
    trendLabel: "Growing",
    difficulty: "Advanced",
    estimatedMonths: 6,
    summary: "Operate container orchestration platforms with reliability and security.",
    whyNow: "Teams are standardizing deployment and runtime operations on Kubernetes.",
    tags: ["kubernetes", "containers", "platform", "ops"],
    roadmapMilestones: [
      "Learn container runtime and image fundamentals",
      "Deploy workloads with Pods, Deployments, and Services",
      "Manage config and secrets safely",
      "Implement ingress and service mesh basics",
      "Set up autoscaling and resource policies",
      "Use Helm and GitOps deployment patterns",
      "Secure clusters with RBAC and policies",
      "Monitor workloads with Prometheus and Grafana",
      "Handle upgrades and multi-cluster strategies",
      "Run production incident response drills",
    ],
    resources: {
      officialDocs: [
        link("Kubernetes Docs", "https://kubernetes.io/docs/home/", "Kubernetes"),
        link("Helm Docs", "https://helm.sh/docs/", "Helm"),
      ],
      youtubeChannels: [
        link("TechWorld with Nana", "https://www.youtube.com/@TechWorldwithNana", "TechWorld with Nana"),
        link("KodeKloud", "https://www.youtube.com/@KodeKloud", "KodeKloud"),
      ],
      labsHandsOn: [
        link("Play with Kubernetes", "https://labs.play-with-k8s.com/", "Docker"),
      ],
      roadmaps: [
        link("Kubernetes Roadmap", "https://roadmap.sh/kubernetes", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("CNCF Blog", "https://www.cncf.io/blog/", "CNCF"),
        link("Kubernetes Patterns", "https://kubernetes.io/blog/", "Kubernetes"),
      ],
      projectIdeas: [
        "Run a multi-service app on Kubernetes with autoscaling",
        "Build a GitOps-driven deployment pipeline for K8s",
      ],
    },
  },
  {
    id: "devops-sre-foundations",
    title: "DevOps and SRE Foundations",
    domain: "DevOps",
    demandScore: 90,
    trendLabel: "High Demand",
    difficulty: "Intermediate",
    estimatedMonths: 5,
    summary: "Improve delivery speed and reliability through automation, monitoring, and SRE practices.",
    whyNow: "Organizations prioritize uptime and delivery efficiency at the same time.",
    tags: ["devops", "sre", "ci/cd", "automation", "reliability"],
    roadmapMilestones: [
      "Understand DevOps lifecycle and value stream",
      "Build CI pipelines with tests and quality gates",
      "Implement CD strategies and approvals",
      "Learn IaC workflows with Terraform",
      "Define SLOs, SLIs, and error budgets",
      "Set up observability dashboards and alerts",
      "Automate rollback and incident response",
      "Run postmortems and reliability reviews",
      "Optimize release flow and deployment frequency",
      "Operate production services with SRE mindset",
    ],
    resources: {
      officialDocs: [
        link("Terraform Docs", "https://developer.hashicorp.com/terraform/docs", "HashiCorp"),
        link("Google SRE", "https://sre.google/", "Google"),
      ],
      youtubeChannels: [
        link("DevOps Toolkit", "https://www.youtube.com/@DevOpsToolkit", "DevOps Toolkit"),
        link("Google Cloud Tech", "https://www.youtube.com/@googlecloudtech", "Google Cloud"),
      ],
      labsHandsOn: [
        link("Katacoda DevOps Scenarios", "https://www.katacoda.com/courses/devops", "Katacoda"),
      ],
      roadmaps: [
        link("DevOps Roadmap", "https://roadmap.sh/devops", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("The Twelve-Factor App", "https://12factor.net/", "12factor"),
        link("GitHub Actions Docs", "https://docs.github.com/actions", "GitHub"),
      ],
      projectIdeas: [
        "Implement CI/CD for a microservice app with rollback",
        "Create an SLO dashboard and incident playbook",
      ],
    },
  },
  {
    id: "cybersecurity-engineering",
    title: "Cybersecurity Engineering",
    domain: "Security",
    demandScore: 94,
    trendLabel: "Critical",
    difficulty: "Intermediate",
    estimatedMonths: 6,
    summary: "Build secure systems through threat modeling, hardening, and continuous security testing.",
    whyNow: "Security skills are mandatory as attack surfaces grow across cloud and AI systems.",
    tags: ["security", "appsec", "cloud security", "threat modeling"],
    roadmapMilestones: [
      "Learn security fundamentals and common vulnerabilities",
      "Apply OWASP Top 10 practices",
      "Implement secure authentication and session controls",
      "Use static and dynamic security testing",
      "Harden containers and cloud infrastructure",
      "Manage secrets and key rotation",
      "Run threat modeling for key workflows",
      "Set up SIEM alerting and response basics",
      "Practice incident response and communication",
      "Conduct security reviews before release",
    ],
    resources: {
      officialDocs: [
        link("OWASP Top 10", "https://owasp.org/www-project-top-ten/", "OWASP"),
        link("NIST Cybersecurity Framework", "https://www.nist.gov/cyberframework", "NIST"),
      ],
      youtubeChannels: [
        link("John Hammond", "https://www.youtube.com/@_JohnHammond", "John Hammond"),
        link("LiveOverflow", "https://www.youtube.com/@LiveOverflow", "LiveOverflow"),
      ],
      labsHandsOn: [
        link("PortSwigger Web Security Academy", "https://portswigger.net/web-security", "PortSwigger"),
      ],
      roadmaps: [
        link("Cyber Security Roadmap", "https://roadmap.sh/cyber-security", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("Cloud Security Alliance", "https://cloudsecurityalliance.org/research", "CSA"),
        link("Google Security Blog", "https://security.googleblog.com/", "Google"),
      ],
      projectIdeas: [
        "Add threat modeling and SAST to a CI pipeline",
        "Create a secure auth gateway with audit logging",
      ],
    },
  },
  {
    id: "frontend-architecture-react",
    title: "Frontend Architecture with React",
    domain: "Frontend",
    demandScore: 87,
    trendLabel: "Strong Demand",
    difficulty: "Intermediate",
    estimatedMonths: 4,
    summary: "Build maintainable frontend systems with performance, accessibility, and design consistency.",
    whyNow: "Complex web products need scalable frontend architecture, not only components.",
    tags: ["frontend", "react", "architecture", "performance", "a11y"],
    roadmapMilestones: [
      "Master React rendering and state fundamentals",
      "Organize feature-first frontend architecture",
      "Implement design system primitives",
      "Handle data fetching and cache patterns",
      "Optimize performance and bundle size",
      "Apply accessibility and keyboard navigation",
      "Set up frontend testing strategy",
      "Define error boundaries and resilience",
      "Improve observability for web vitals",
      "Ship a production-grade frontend module",
    ],
    resources: {
      officialDocs: [
        link("React Docs", "https://react.dev/", "React"),
        link("Web.dev Performance", "https://web.dev/learn/performance", "Google"),
      ],
      youtubeChannels: [
        link("Web Dev Simplified", "https://www.youtube.com/@WebDevSimplified", "Web Dev Simplified"),
        link("Jack Herrington", "https://www.youtube.com/@JackHerrington", "Jack Herrington"),
      ],
      labsHandsOn: [
        link("Frontend Mentor", "https://www.frontendmentor.io/", "Frontend Mentor"),
      ],
      roadmaps: [
        link("Frontend Roadmap", "https://roadmap.sh/frontend", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("MDN Web Docs", "https://developer.mozilla.org/", "MDN"),
        link("WAI Accessibility Tutorials", "https://www.w3.org/WAI/tutorials/", "W3C"),
      ],
      projectIdeas: [
        "Build an accessible design system starter",
        "Create a dashboard optimized for Core Web Vitals",
      ],
    },
  },
  {
    id: "nextjs-fullstack-apps",
    title: "Next.js Full-Stack Web Apps",
    domain: "Frontend",
    demandScore: 89,
    trendLabel: "Trending",
    difficulty: "Intermediate",
    estimatedMonths: 4,
    summary: "Ship full-stack applications with modern routing, server actions, and production deployment.",
    whyNow: "Full-stack React frameworks are now default choices for many teams.",
    tags: ["next.js", "react", "fullstack", "web", "typescript"],
    roadmapMilestones: [
      "Understand App Router architecture",
      "Build server and client component boundaries",
      "Implement authentication and session management",
      "Design API routes and server actions",
      "Optimize caching and revalidation",
      "Add form handling and validation",
      "Integrate database persistence",
      "Set up observability and analytics",
      "Harden security headers and protections",
      "Deploy and monitor production environment",
    ],
    resources: {
      officialDocs: [
        link("Next.js Docs", "https://nextjs.org/docs", "Vercel"),
        link("TypeScript Handbook", "https://www.typescriptlang.org/docs/", "TypeScript"),
      ],
      youtubeChannels: [
        link("Vercel", "https://www.youtube.com/@VercelHQ", "Vercel"),
        link("Theo - t3.gg", "https://www.youtube.com/@t3dotgg", "t3.gg"),
      ],
      labsHandsOn: [
        link("Next.js Learn", "https://nextjs.org/learn", "Vercel"),
      ],
      roadmaps: [
        link("Full Stack Roadmap", "https://roadmap.sh/full-stack", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("Vercel Blog", "https://vercel.com/blog", "Vercel"),
        link("Prisma Guides", "https://www.prisma.io/docs/guides", "Prisma"),
      ],
      projectIdeas: [
        "Build a SaaS starter with auth and billing hooks",
        "Create a multi-tenant admin analytics app",
      ],
    },
  },
  {
    id: "flutter-mobile-development",
    title: "Mobile Development with Flutter",
    domain: "Mobile",
    demandScore: 84,
    trendLabel: "Steady Demand",
    difficulty: "Beginner",
    estimatedMonths: 5,
    summary: "Develop cross-platform mobile apps with polished UI and production-quality architecture.",
    whyNow: "Cross-platform speed and quality make Flutter attractive for product teams.",
    tags: ["flutter", "mobile", "dart", "cross-platform"],
    roadmapMilestones: [
      "Learn Dart programming essentials",
      "Build Flutter layouts and navigation",
      "Manage state with provider or bloc",
      "Integrate REST and local persistence",
      "Handle forms, validation, and errors",
      "Apply animations and responsive design",
      "Add authentication and secure storage",
      "Write widget and integration tests",
      "Prepare app release and store assets",
      "Ship and monitor a real mobile app",
    ],
    resources: {
      officialDocs: [
        link("Flutter Docs", "https://docs.flutter.dev/", "Flutter"),
        link("Dart Docs", "https://dart.dev/guides", "Dart"),
      ],
      youtubeChannels: [
        link("Flutter", "https://www.youtube.com/@flutterdev", "Flutter"),
        link("CodeWithAndrea", "https://www.youtube.com/@CodeWithAndrea", "CodeWithAndrea"),
      ],
      labsHandsOn: [
        link("Flutter Codelabs", "https://codelabs.developers.google.com/?cat=Flutter", "Google"),
      ],
      roadmaps: [
        link("Flutter Roadmap", "https://roadmap.sh/flutter", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("Flutter Cookbook", "https://docs.flutter.dev/cookbook", "Flutter"),
        link("Very Good Ventures Guides", "https://verygood.ventures/blog", "Very Good Ventures"),
      ],
      projectIdeas: [
        "Build a habit tracker with offline sync",
        "Create a mobile learning planner with reminders",
      ],
    },
  },
  {
    id: "react-native-mobile-development",
    title: "Mobile Development with React Native",
    domain: "Mobile",
    demandScore: 85,
    trendLabel: "Growing",
    difficulty: "Intermediate",
    estimatedMonths: 5,
    summary: "Build cross-platform mobile apps with JavaScript/TypeScript and native integrations.",
    whyNow: "Teams with web React expertise can move quickly into mobile with React Native.",
    tags: ["react native", "mobile", "react", "typescript"],
    roadmapMilestones: [
      "Set up React Native development workflow",
      "Build navigation and shared UI components",
      "Handle state and async data patterns",
      "Integrate native device capabilities",
      "Manage performance and memory hotspots",
      "Implement authentication and secure tokens",
      "Add offline caching strategies",
      "Write unit and E2E tests",
      "Prepare Android and iOS release pipelines",
      "Launch and monitor production app",
    ],
    resources: {
      officialDocs: [
        link("React Native Docs", "https://reactnative.dev/docs/getting-started", "React Native"),
        link("Expo Docs", "https://docs.expo.dev/", "Expo"),
      ],
      youtubeChannels: [
        link("notJust.dev", "https://www.youtube.com/@notjustdev", "notJust.dev"),
        link("William Candillon", "https://www.youtube.com/@wcandillon", "William Candillon"),
      ],
      labsHandsOn: [
        link("Expo Tutorials", "https://docs.expo.dev/tutorial/introduction/", "Expo"),
      ],
      roadmaps: [
        link("React Native Roadmap", "https://roadmap.sh/react-native", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("React Native Blog", "https://reactnative.dev/blog", "React Native"),
        link("Callstack Articles", "https://www.callstack.com/blog", "Callstack"),
      ],
      projectIdeas: [
        "Build a social feed app with push notifications",
        "Create a delivery tracker with maps and live status",
      ],
    },
  },
  {
    id: "database-engineering-sql-performance",
    title: "Database Engineering and SQL Performance",
    domain: "Data",
    demandScore: 86,
    trendLabel: "Core Skill",
    difficulty: "Intermediate",
    estimatedMonths: 4,
    summary: "Design robust schemas, optimize queries, and operate database systems reliably.",
    whyNow: "Performance and data correctness remain major bottlenecks in scaling products.",
    tags: ["sql", "database", "postgres", "indexing", "performance"],
    roadmapMilestones: [
      "Model relational schemas and constraints",
      "Write advanced SQL joins and windows",
      "Design indexing and query plans",
      "Tune transaction and isolation behavior",
      "Implement backup and recovery strategies",
      "Scale read/write workloads",
      "Use migrations and schema versioning",
      "Add observability for DB performance",
      "Handle multi-tenant data boundaries",
      "Run database reliability reviews",
    ],
    resources: {
      officialDocs: [
        link("PostgreSQL Docs", "https://www.postgresql.org/docs/", "PostgreSQL"),
        link("MongoDB Docs", "https://www.mongodb.com/docs/", "MongoDB"),
      ],
      youtubeChannels: [
        link("Hussein Nasser", "https://www.youtube.com/@hnasr", "Hussein Nasser"),
        link("ByteByteGo", "https://www.youtube.com/@ByteByteGo", "ByteByteGo"),
      ],
      labsHandsOn: [
        link("SQLBolt", "https://sqlbolt.com/", "SQLBolt"),
      ],
      roadmaps: [
        link("SQL Roadmap", "https://roadmap.sh/sql", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("Use The Index, Luke", "https://use-the-index-luke.com/", "Markus Winand"),
        link("Planet PostgreSQL", "https://planet.postgresql.org/", "PostgreSQL Community"),
      ],
      projectIdeas: [
        "Optimize a slow reporting workload with indexing",
        "Build a backup and recovery drill pipeline",
      ],
    },
  },
  {
    id: "observability-engineering",
    title: "Observability Engineering",
    domain: "DevOps",
    demandScore: 88,
    trendLabel: "Rising",
    difficulty: "Intermediate",
    estimatedMonths: 4,
    summary: "Implement logs, metrics, traces, and alerting that accelerate debugging and reliability.",
    whyNow: "Complex distributed systems require deep visibility to operate confidently.",
    tags: ["observability", "monitoring", "tracing", "sre"],
    roadmapMilestones: [
      "Define telemetry standards across services",
      "Instrument application logs with context",
      "Expose service-level metrics",
      "Add distributed tracing",
      "Create SLO-aligned dashboards",
      "Design actionable alert policies",
      "Correlate incidents across signals",
      "Reduce noisy alerts and false positives",
      "Integrate observability into incident workflow",
      "Run reliability reviews using observability data",
    ],
    resources: {
      officialDocs: [
        link("OpenTelemetry Docs", "https://opentelemetry.io/docs/", "OpenTelemetry"),
        link("Prometheus Docs", "https://prometheus.io/docs/introduction/overview/", "Prometheus"),
      ],
      youtubeChannels: [
        link("Grafana", "https://www.youtube.com/@Grafana", "Grafana"),
        link("Honeycomb", "https://www.youtube.com/@honeycombio", "Honeycomb"),
      ],
      labsHandsOn: [
        link("OpenTelemetry Demos", "https://github.com/open-telemetry/opentelemetry-demo", "OpenTelemetry"),
      ],
      roadmaps: [
        link("DevOps Roadmap", "https://roadmap.sh/devops", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("Google SRE Monitoring", "https://sre.google/sre-book/monitoring-distributed-systems/", "Google"),
        link("Grafana Labs Blog", "https://grafana.com/blog/", "Grafana"),
      ],
      projectIdeas: [
        "Instrument a service with traces and SLO dashboard",
        "Build an alert tuning workflow to reduce noise",
      ],
    },
  },
  {
    id: "platform-engineering-idp",
    title: "Platform Engineering and Internal Developer Platforms",
    domain: "Platform",
    demandScore: 87,
    trendLabel: "Growing",
    difficulty: "Advanced",
    estimatedMonths: 6,
    summary: "Create self-service internal platforms that improve engineering velocity and reliability.",
    whyNow: "Organizations are investing in platform teams to scale product delivery.",
    tags: ["platform engineering", "idp", "developer experience", "golden paths"],
    roadmapMilestones: [
      "Assess current developer workflow bottlenecks",
      "Define platform product strategy and KPIs",
      "Design self-service templates and guardrails",
      "Implement service catalog and ownership model",
      "Automate environment provisioning",
      "Create secure golden paths for deployments",
      "Integrate policy-as-code controls",
      "Measure adoption and developer satisfaction",
      "Iterate with product-style platform roadmap",
      "Scale IDP operations across teams",
    ],
    resources: {
      officialDocs: [
        link("Backstage Docs", "https://backstage.io/docs/", "Backstage"),
        link("CNCF Platform Whitepapers", "https://www.cncf.io/reports/", "CNCF"),
      ],
      youtubeChannels: [
        link("Platform Engineering", "https://www.youtube.com/@PlatformEngineering", "Platform Engineering"),
        link("CNCF", "https://www.youtube.com/@cncf", "CNCF"),
      ],
      labsHandsOn: [
        link("Backstage Demo", "https://demo.backstage.io/", "Backstage"),
      ],
      roadmaps: [
        link("DevOps Roadmap", "https://roadmap.sh/devops", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("Thoughtworks Technology Radar", "https://www.thoughtworks.com/radar", "Thoughtworks"),
        link("Humanitec Platform Engineering Guide", "https://humanitec.com/blog", "Humanitec"),
      ],
      projectIdeas: [
        "Create an internal service template with CI/CD and observability",
        "Build a developer portal for service discovery and docs",
      ],
    },
  },
  {
    id: "api-design-integration-architecture",
    title: "API Design and Integration Architecture",
    domain: "Backend",
    demandScore: 86,
    trendLabel: "Core",
    difficulty: "Intermediate",
    estimatedMonths: 4,
    summary: "Design APIs and integrations that scale across teams, partners, and products.",
    whyNow: "Integration complexity keeps rising with microservices and partner ecosystems.",
    tags: ["api", "integration", "architecture", "backend"],
    roadmapMilestones: [
      "Model domain boundaries and API contracts",
      "Apply REST and event-driven design principles",
      "Version APIs safely",
      "Implement authn/authz patterns for integrations",
      "Design webhook and async processing reliability",
      "Use schema governance and linting",
      "Handle idempotency and retries",
      "Create API documentation and SDK guidance",
      "Track API analytics and error budgets",
      "Run breaking-change reviews",
    ],
    resources: {
      officialDocs: [
        link("OpenAPI Specification", "https://spec.openapis.org/oas/latest.html", "OpenAPI Initiative"),
        link("AsyncAPI Docs", "https://www.asyncapi.com/docs", "AsyncAPI"),
      ],
      youtubeChannels: [
        link("API University", "https://www.youtube.com/@API-University", "API University"),
        link("Nordic APIs", "https://www.youtube.com/@NordicAPIs", "Nordic APIs"),
      ],
      labsHandsOn: [
        link("Postman Learning Center", "https://learning.postman.com/", "Postman"),
      ],
      roadmaps: [
        link("Backend Roadmap", "https://roadmap.sh/backend", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("Stripe API Blog", "https://stripe.com/blog/topics/api", "Stripe"),
        link("Microsoft API Guidelines", "https://github.com/microsoft/api-guidelines", "Microsoft"),
      ],
      projectIdeas: [
        "Design a public API with rate limits and usage analytics",
        "Build webhook retries with dead-letter handling",
      ],
    },
  },
  {
    id: "prompt-engineering-product",
    title: "Prompt Engineering for Product Teams",
    domain: "AI",
    demandScore: 83,
    trendLabel: "Emerging",
    difficulty: "Beginner",
    estimatedMonths: 3,
    summary: "Create reliable prompt systems for product features and operations workflows.",
    whyNow: "Teams need practical prompt quality and safety workflows across departments.",
    tags: ["prompt engineering", "llm", "ai", "fundamentals"],
    roadmapMilestones: [
      "Understand prompting patterns and failure modes",
      "Define structured output requirements",
      "Create reusable prompt templates",
      "Build context assembly pipelines",
      "Implement validation and fallback prompts",
      "Apply safety and policy constraints",
      "Run prompt experiments and A/B tests",
      "Track quality and drift over time",
      "Document prompt playbooks for teams",
      "Ship one production prompt workflow",
    ],
    resources: {
      officialDocs: [
        link("OpenAI Prompting Guide", "https://platform.openai.com/docs/guides/prompt-engineering", "OpenAI"),
        link("Anthropic Prompt Guides", "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview", "Anthropic"),
      ],
      youtubeChannels: [
        link("DeepLearningAI", "https://www.youtube.com/@Deeplearningai", "DeepLearningAI"),
        link("The AI Advantage", "https://www.youtube.com/@TheAIAadvantage", "The AI Advantage"),
      ],
      labsHandsOn: [
        link("OpenAI Cookbook", "https://cookbook.openai.com/", "OpenAI"),
      ],
      roadmaps: [
        link("Prompt Engineering Roadmap", "https://roadmap.sh/prompt-engineering", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("Prompting Guide", "https://www.promptingguide.ai/", "Prompting Guide"),
        link("Learn Prompting", "https://learnprompting.org/", "Learn Prompting"),
      ],
      projectIdeas: [
        "Build a prompt QA toolkit for support responses",
        "Create a structured extraction workflow for operations docs",
      ],
    },
  },
  {
    id: "genai-product-engineering",
    title: "Generative AI Product Engineering",
    domain: "AI",
    demandScore: 96,
    trendLabel: "Surging",
    difficulty: "Advanced",
    estimatedMonths: 6,
    summary: "Build end-to-end GenAI features with product metrics, safety, and operational controls.",
    whyNow: "Winning products differentiate by real GenAI user value, not demos.",
    tags: ["genai", "product", "ai", "evaluation", "safety"],
    roadmapMilestones: [
      "Identify high-value GenAI product use cases",
      "Define success metrics for AI features",
      "Design data and prompt architecture",
      "Build retrieval and tool integration layers",
      "Implement evaluation harnesses",
      "Add trust, safety, and governance checks",
      "Optimize latency and cost tradeoffs",
      "Instrument user feedback loops",
      "Run phased rollout experiments",
      "Scale and iterate based on product outcomes",
    ],
    resources: {
      officialDocs: [
        link("OpenAI Best Practices", "https://platform.openai.com/docs/guides/production-best-practices", "OpenAI"),
        link("Google Responsible AI", "https://ai.google/responsibility/", "Google"),
      ],
      youtubeChannels: [
        link("OpenAI", "https://www.youtube.com/@OpenAI", "OpenAI"),
        link("Weights & Biases", "https://www.youtube.com/@WeightsBiases", "Weights & Biases"),
      ],
      labsHandsOn: [
        link("Weights & Biases Weave", "https://wandb.ai/site/weave", "Weights & Biases"),
      ],
      roadmaps: [
        link("AI Engineer Roadmap", "https://roadmap.sh/ai-engineer", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("Latent Space", "https://www.latent.space/", "Latent Space"),
        link("LangSmith Guides", "https://docs.smith.langchain.com/", "LangChain"),
      ],
      projectIdeas: [
        "Launch a GenAI support co-pilot with human escalation",
        "Build an AI writing assistant with measurable quality goals",
      ],
    },
  },
  {
    id: "container-security-supply-chain",
    title: "Container Security and Supply Chain",
    domain: "Security",
    demandScore: 85,
    trendLabel: "Rising",
    difficulty: "Advanced",
    estimatedMonths: 5,
    summary: "Secure containers, dependencies, and CI pipelines against modern supply-chain risks.",
    whyNow: "Containerized production environments increase dependency and image security risk.",
    tags: ["containers", "security", "supply chain", "devsecops"],
    roadmapMilestones: [
      "Understand software supply chain attack vectors",
      "Scan dependencies and container images",
      "Sign and verify build artifacts",
      "Enforce policy-as-code in CI pipelines",
      "Harden base images and runtime configs",
      "Protect secrets and identity in pipelines",
      "Implement SBOM generation and tracking",
      "Monitor runtime behavior for anomalies",
      "Build incident response for supply-chain issues",
      "Run continuous security posture reviews",
    ],
    resources: {
      officialDocs: [
        link("SLSA Framework", "https://slsa.dev/", "SLSA"),
        link("NIST SSDF", "https://csrc.nist.gov/Projects/ssdf", "NIST"),
      ],
      youtubeChannels: [
        link("OWASP", "https://www.youtube.com/@OWASPGlobal", "OWASP"),
        link("Aqua Security", "https://www.youtube.com/@AquaSecurity", "Aqua"),
      ],
      labsHandsOn: [
        link("Docker Security Labs", "https://www.docker.com/resources/", "Docker"),
      ],
      roadmaps: [
        link("Cyber Security Roadmap", "https://roadmap.sh/cyber-security", "roadmap.sh"),
      ],
      blogsAndGuides: [
        link("CISA Secure by Design", "https://www.cisa.gov/securebydesign", "CISA"),
        link("Chainguard Academy", "https://edu.chainguard.dev/", "Chainguard"),
      ],
      projectIdeas: [
        "Add SBOM and image signing to a CI pipeline",
        "Build runtime policy alerts for container clusters",
      ],
    },
  },
]

export const recommendationDomains = [
  "All",
  "AI",
  "Backend",
  "Cloud",
  "Containers",
  "Data",
  "Security",
  "DevOps",
  "Frontend",
  "Mobile",
  "Architecture",
  "Platform",
] as const

